import { useEffect, useState } from "react";

import { listWorkflowEvaluationCases, type WorkflowEvaluationCase } from "./workflowEvaluationConsumer.ts";
import { createWorkflowEvaluationSuite, decideWorkflowEvaluationSuite, listWorkflowEvaluationDecisions, listWorkflowEvaluationSuites, reviewWorkflowEvaluationSuite, WorkflowEvaluationDecisionConflict, type WorkflowEvaluationReleaseDecision, type WorkflowEvaluationReleaseDecisionKind, type WorkflowEvaluationSuite, type WorkflowEvaluationSuiteCaseRef, type WorkflowEvaluationSuiteReview } from "./workflowEvaluationSuiteConsumer.ts";
import type { WorkflowExecutorConsumerConfig } from "./workflowExecutorConsumer.ts";

export default function WorkflowEvaluationSuitePanel({applicationId,config}:{applicationId:string;config:WorkflowExecutorConsumerConfig}) {
  const [cases,setCases]=useState<WorkflowEvaluationCase[]>([]), [suites,setSuites]=useState<WorkflowEvaluationSuite[]>([]), [name,setName]=useState(""), [caseId,setCaseId]=useState(""), [version,setVersion]=useState(1), [refs,setRefs]=useState<WorkflowEvaluationSuiteCaseRef[]>([]);
  const [selected,setSelected]=useState<WorkflowEvaluationSuite|null>(null), [review,setReview]=useState<WorkflowEvaluationSuiteReview|null>(null), [decisions,setDecisions]=useState<WorkflowEvaluationReleaseDecision[]>([]), [decision,setDecision]=useState<WorkflowEvaluationReleaseDecisionKind>("needs_review"), [failure,setFailure]=useState("");

  async function refresh(){try{const [casePage,suitePage]=await Promise.all([listWorkflowEvaluationCases(applicationId,config),listWorkflowEvaluationSuites(applicationId,config)]);setCases(casePage.cases);setSuites(suitePage.suites)}catch(error){setFailure(message(error,"Evaluation suites unavailable."))}}
  useEffect(()=>{void refresh()},[applicationId]);
  function chooseCase(value:string){setCaseId(value);const found=cases.find(item=>item.caseId===value);if(found)setVersion(found.version)}
  function addRef(){if(!caseId||version<1||refs.some(item=>item.caseId===caseId&&item.version===version))return;setRefs([...refs,{caseId,version}])}
  async function create(){setFailure("");try{await createWorkflowEvaluationSuite(applicationId,name,refs,config);setName("");setRefs([]);await refresh()}catch(error){setFailure(message(error,"Evaluation suite creation failed."))}}
  async function inspect(value:WorkflowEvaluationSuite){setFailure("");setSelected(value);try{const [nextReview,history]=await Promise.all([reviewWorkflowEvaluationSuite(applicationId,value.suiteId,config),listWorkflowEvaluationDecisions(applicationId,value.suiteId,config)]);setReview(nextReview);setDecisions(history.decisions)}catch(error){setFailure(message(error,"Release review failed."))}}
  async function recordDecision(){if(!selected||!review)return;setFailure("");try{const result=await decideWorkflowEvaluationSuite(applicationId,selected.suiteId,selected.currentDecisionVersion,decision,review.reviewDigest,config);setSelected(result.suite);await refresh();await inspect(result.suite)}catch(error){if(error instanceof WorkflowEvaluationDecisionConflict){setSelected(error.currentSuite);await refresh();await inspect(error.currentSuite)}setFailure(message(error,"Release decision failed."))}}

  return <section className="workflow-evaluation-panel" aria-labelledby="workflow-evaluation-suite-title">
    <div className="card-title-row"><div><p className="eyebrow">Durable release evidence</p><h4 id="workflow-evaluation-suite-title">Evaluation suites</h4></div><div><span className="status-badge status-neutral">review only</span><button type="button" onClick={()=>void refresh()}>Refresh cases and suites</button></div></div>
    <p>Suites bind exact case versions. Decisions retain the reviewed digest and never deploy, execute, replay, confirm, call tools, or write business data.</p>
    <div className="workflow-run-comparison-selector">
      <label>Suite name<input value={name} onChange={event=>setName(event.target.value)} placeholder="release candidate review" /></label>
      <label>Evaluation case<select value={caseId} onChange={event=>chooseCase(event.target.value)}><option value="">Choose exact case</option>{cases.map(item=><option key={item.caseId} value={item.caseId}>{item.name} · current v{item.version}</option>)}</select></label>
      <label>Version<input type="number" min="1" value={version} onChange={event=>setVersion(Number(event.target.value))} /></label>
      <button type="button" disabled={!caseId||version<1} onClick={addRef}>Add exact version</button>
    </div>
    <div className="workflow-evaluation-expectations">{refs.map(item=><span className="status-badge status-neutral" key={`${item.caseId}-${item.version}`}>{item.caseId} · v{item.version} <button type="button" onClick={()=>setRefs(refs.filter(ref=>ref!==item))}>Remove</button></span>)}</div>
    <button type="button" disabled={!name.trim()||refs.length===0} onClick={()=>void create()}>Create evaluation suite</button>
    {failure?<p className="failure-summary">{failure}</p>:null}
    <div className="workflow-run-history-live-list" aria-label="Workflow evaluation suite history">{suites.map(item=><button type="button" className={`workflow-run-history-live-row ${selected?.suiteId===item.suiteId?"is-selected":""}`} key={item.suiteId} onClick={()=>void inspect(item)}><span className="workflow-run-history-live-identity"><strong>{item.name}</strong><small>{item.suiteId}</small></span><span><small>Cases</small><strong>{item.caseRefs.length}</strong></span><span><small>Decision</small><strong>{item.currentDecision||"unreviewed"}</strong><small>version {item.currentDecisionVersion}</small></span></button>)}</div>
    {selected&&review?<article className="workflow-evaluation-review"><div className="card-title-row"><div><p className="eyebrow">Aggregate release review</p><h5>{review.outcome}</h5></div><span className={`status-badge ${review.outcome==="passed"?"status-good":"status-neutral"}`}>{review.passed} passed</span></div><dl className="tenant-meta"><div><dt>Mismatch</dt><dd>{review.mismatch}</dd></div><div><dt>Inconclusive</dt><dd>{review.inconclusive}</dd></div><div><dt>Unavailable</dt><dd>{review.unavailable}</dd></div><div><dt>Digest</dt><dd>{review.reviewDigest.slice(0,12)}…</dd></div></dl>{review.items.map(item=><div className="workflow-evaluation-review-item" key={`${item.caseId}-${item.version}`}><strong>{item.name||item.caseId}</strong><span>{item.caseId} · v{item.version}</span><span>{item.outcome} · {item.runProfile}</span></div>)}<div className="workflow-run-comparison-selector"><label>Human decision<select value={decision} onChange={event=>setDecision(event.target.value as WorkflowEvaluationReleaseDecisionKind)}><option value="needs_review">Needs review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><button type="button" onClick={()=>void recordDecision()}>Record decision v{selected.currentDecisionVersion+1}</button></div><div className="workflow-run-history-live-list" aria-label="Release decision evidence">{decisions.map(item=><div className="workflow-run-history-live-row" key={item.decisionId}><span><strong>v{item.version} · {item.decision}</strong><small>{item.createdAt}</small></span><span><small>Reviewed</small><strong>{item.reviewOutcome}</strong></span><span><small>Digest</small><strong>{item.reviewDigest.slice(0,12)}…</strong></span></div>)}</div><p className="boundary-note">Approval is evidence only. Retrieval profiles remain metadata-only; production enablement and all side-effect capabilities remain closed.</p></article>:null}
  </section>
}

function message(error:unknown,fallback:string){return error instanceof Error?error.message:fallback}
