import type { WorkflowExecutorConsumerConfig } from "./workflowExecutorConsumer.ts";

export type WorkflowEvaluationClassification="regression"|"improvement"|"changed"|"unchanged";
export type WorkflowEvaluationExpectation={candidateRunId:string;expectedClassification:WorkflowEvaluationClassification};
export type WorkflowEvaluationRevisionKind="created"|"baseline_promotion"|"case_revision";
export type WorkflowEvaluationCase={caseId:string;version:number;previousVersion:number;revisionKind:WorkflowEvaluationRevisionKind;changeCodes:string[];name:string;baselineRunId:string;expectations:WorkflowEvaluationExpectation[];createdAt:string;revisedAt:string;actorRef:string;requestId:string;auditRef:string};
export type WorkflowEvaluationReviewItem={candidateRunId:string;expectedClassification:string;actualClassification:string;comparisonState:string;comparisonSchemaVersion:"workflow_run_comparison.v1"|"workflow_run_comparison.v2"|"workflow_run_comparison.v3"|"";runProfile:"workflow_standard.v1"|"workflow_rag_retrieval.v1"|"workflow_rag_application_invocation.v1"|"unavailable";outcome:"matched"|"mismatched"|"inconclusive"|"unavailable";findingCodes:string[];recommendedReviewAction:string};
export type WorkflowEvaluationReview={caseId:string;version:number;runProfile:"workflow_standard.v1"|"workflow_rag_retrieval.v1"|"workflow_rag_application_invocation.v1"|"unavailable";outcome:"passed"|"mismatch"|"inconclusive";matched:number;mismatched:number;inconclusive:number;unavailable:number;items:WorkflowEvaluationReviewItem[]};
export type WorkflowEvaluationRevisionInput={expectedVersion:number;revisionKind:Exclude<WorkflowEvaluationRevisionKind,"created">;name:string;baselineRunId:string;expectations:WorkflowEvaluationExpectation[]};
type CaseDocument={schema_version:"workflow_evaluation_case.v2";case_id:string;version:number;previous_version:number;revision_kind:WorkflowEvaluationRevisionKind;change_codes:string[];name:string;workspace_id:string;application_id:string;baseline_run_id:string;expectations:Array<{candidate_run_id:string;expected_classification:WorkflowEvaluationClassification}>;created_at:string;revised_at:string;actor_ref:string;request_id:string;audit_ref:string};
type ReviewDocument={case_id:string;version:number;run_profile:WorkflowEvaluationReview["runProfile"];outcome:WorkflowEvaluationReview["outcome"];matched:number;mismatched:number;inconclusive:number;unavailable:number;items:Array<{candidate_run_id:string;expected_classification:string;actual_classification:string;comparison_state:string;comparison_schema_version:WorkflowEvaluationReviewItem["comparisonSchemaVersion"];run_profile:WorkflowEvaluationReviewItem["runProfile"];outcome:WorkflowEvaluationReviewItem["outcome"];finding_codes:string[];recommended_review_action:string}>};
type Envelope={request_id:string;workspace_id:string;application_id:string;case:CaseDocument|null;review:ReviewDocument|null;failure_code:string|null;failure_summary:string;audit_ref:string};
type ListEnvelope={request_id:string;workspace_id:string;application_id:string;cases:CaseDocument[];next_cursor:string;has_more:boolean;failure_code:string|null;failure_summary:string;audit_ref:string};
type RevisionListEnvelope={request_id:string;workspace_id:string;application_id:string;revisions:CaseDocument[];next_cursor:string;has_more:boolean;failure_code:string|null;failure_summary:string;audit_ref:string};

export class WorkflowEvaluationVersionConflict extends Error{readonly currentCase:WorkflowEvaluationCase;constructor(currentCase:WorkflowEvaluationCase){super("Workflow evaluation changed; review the current version before revising.");this.name="WorkflowEvaluationVersionConflict";this.currentCase=currentCase}}

export async function createWorkflowEvaluationCase(applicationId:string,name:string,baselineRunId:string,expectations:WorkflowEvaluationExpectation[],config:WorkflowExecutorConsumerConfig):Promise<WorkflowEvaluationCase>{assertLive(config);return writeCase(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases`,applicationId,{workspace_id:config.workspaceId,application_id:applicationId,name,baseline_run_id:baselineRunId,expectations:mapExpectations(expectations)},config)}
export async function reviseWorkflowEvaluationCase(applicationId:string,caseId:string,input:WorkflowEvaluationRevisionInput,config:WorkflowExecutorConsumerConfig):Promise<WorkflowEvaluationCase>{assertLive(config);return writeCase(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases/${encodeURIComponent(caseId)}/revisions`,applicationId,{workspace_id:config.workspaceId,application_id:applicationId,expected_version:input.expectedVersion,revision_kind:input.revisionKind,name:input.name,baseline_run_id:input.baselineRunId,expectations:mapExpectations(input.expectations)},config)}
async function writeCase(url:string,applicationId:string,payload:unknown,config:WorkflowExecutorConsumerConfig):Promise<WorkflowEvaluationCase>{const response=await fetch(url,{method:"POST",headers:{...evaluationHeaders(config,applicationId,true),"Content-Type":"application/json"},body:JSON.stringify(payload)});const body:unknown=await response.json();if(!response.ok||!isEnvelope(body))throw new Error(envelopeFailure(body,response.status));if(body.failure_code==="workflow_evaluation_version_conflict"&&body.case)throw new WorkflowEvaluationVersionConflict(mapCase(body.case));if(body.failure_code||!body.case)throw new Error(envelopeFailure(body,response.status));return mapCase(body.case)}
export async function listWorkflowEvaluationCases(applicationId:string,config:WorkflowExecutorConsumerConfig,cursor=""):Promise<{cases:WorkflowEvaluationCase[];nextCursor:string;hasMore:boolean}>{if(!isLive(config))return{cases:[],nextCursor:"",hasMore:false};const query=scopedQuery(applicationId,config);query.set("limit","25");if(cursor)query.set("cursor",cursor);const body=await readJSON(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases?${query}`,applicationId,config);if(!isListEnvelope(body)||body.failure_code)throw new Error(envelopeFailure(body,200));return{cases:body.cases.map(mapCase),nextCursor:body.next_cursor,hasMore:body.has_more}}
export async function listWorkflowEvaluationRevisions(applicationId:string,caseId:string,config:WorkflowExecutorConsumerConfig,cursor=""):Promise<{revisions:WorkflowEvaluationCase[];nextCursor:string;hasMore:boolean}>{if(!isLive(config))return{revisions:[],nextCursor:"",hasMore:false};const query=scopedQuery(applicationId,config);query.set("limit","25");if(cursor)query.set("cursor",cursor);const body=await readJSON(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases/${encodeURIComponent(caseId)}/revisions?${query}`,applicationId,config);if(!isRevisionListEnvelope(body)||body.failure_code)throw new Error(envelopeFailure(body,200));return{revisions:body.revisions.map(mapCase),nextCursor:body.next_cursor,hasMore:body.has_more}}
export async function reviewWorkflowEvaluationCase(applicationId:string,caseId:string,config:WorkflowExecutorConsumerConfig,version?:number):Promise<WorkflowEvaluationReview>{assertLive(config);const query=scopedQuery(applicationId,config);if(version)query.set("version",String(version));const body=await readJSON(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases/${encodeURIComponent(caseId)}/review?${query}`,applicationId,config);if(!isEnvelope(body)||body.failure_code||!body.review)throw new Error(envelopeFailure(body,200));return mapReview(body.review)}
async function readJSON(url:string,applicationId:string,config:WorkflowExecutorConsumerConfig):Promise<unknown>{const response=await fetch(url,{headers:evaluationHeaders(config,applicationId,false)});const body:unknown=await response.json();if(!response.ok)throw new Error(envelopeFailure(body,response.status));return body}
function scopedQuery(applicationId:string,config:WorkflowExecutorConsumerConfig){return new URLSearchParams({workspace_id:config.workspaceId,application_id:applicationId})}
function mapExpectations(values:WorkflowEvaluationExpectation[]){return values.map(item=>({candidate_run_id:item.candidateRunId,expected_classification:item.expectedClassification}))}
function isLive(config:WorkflowExecutorConsumerConfig){return config.mode==="dev_workflow_executor_http"}
function assertLive(config:WorkflowExecutorConsumerConfig):asserts config is WorkflowExecutorConsumerConfig{if(!isLive(config))throw new Error("Workflow evaluations are unavailable in offline mode.")}
function evaluationHeaders(config:WorkflowExecutorConsumerConfig,applicationId:string,write:boolean):HeadersInit{return{Accept:"application/json","X-Request-Id":`dev-workflow-evaluation-${applicationId}`,"X-RadishMind-Dev-Read-Identity":"dev-workflow-evaluation-consumer","X-RadishMind-Dev-Read-Tenant":config.tenantRef,"X-RadishMind-Dev-Read-Subject":config.subjectRef,"X-RadishMind-Dev-Read-Scopes":write?"workflow_evaluations:write,workflow_evaluations:read,workflow_runs:read":"workflow_evaluations:read,workflow_runs:read","X-RadishMind-Dev-Read-Audit":"audit_dev_workflow_evaluation_consumer","X-RadishMind-Dev-Workflow-Workspace":config.workspaceId,"X-RadishMind-Dev-Workflow-Application":applicationId}}
function mapCase(value:CaseDocument):WorkflowEvaluationCase{return{caseId:value.case_id,version:value.version,previousVersion:value.previous_version,revisionKind:value.revision_kind,changeCodes:[...value.change_codes],name:value.name,baselineRunId:value.baseline_run_id,expectations:value.expectations.map(item=>({candidateRunId:item.candidate_run_id,expectedClassification:item.expected_classification})),createdAt:value.created_at,revisedAt:value.revised_at,actorRef:value.actor_ref,requestId:value.request_id,auditRef:value.audit_ref}}
function mapReview(value:ReviewDocument):WorkflowEvaluationReview{return{caseId:value.case_id,version:value.version,runProfile:value.run_profile,outcome:value.outcome,matched:value.matched,mismatched:value.mismatched,inconclusive:value.inconclusive,unavailable:value.unavailable,items:value.items.map(item=>({candidateRunId:item.candidate_run_id,expectedClassification:item.expected_classification,actualClassification:item.actual_classification,comparisonState:item.comparison_state,comparisonSchemaVersion:item.comparison_schema_version,runProfile:item.run_profile,outcome:item.outcome,findingCodes:item.finding_codes,recommendedReviewAction:item.recommended_review_action}))}}
function hasForbiddenKey(value:unknown):boolean{if(Array.isArray(value))return value.some(hasForbiddenKey);if(!value||typeof value!=="object")return false;const forbidden=new Set(["input_text","input_bytes","condition_values","condition_node_ids","query","raw_query","fragment_content","content","prompt","prompt_packet","answer","limitations","confidence","output","output_preview","credential","authorization","cookie","endpoint","raw_response","provider_raw_envelope","comparison","change_reason"]);return Object.entries(value as Record<string,unknown>).some(([key,child])=>forbidden.has(key.toLowerCase())||hasForbiddenKey(child))}
function isEnvelope(value:unknown):value is Envelope{if(!value||typeof value!=="object"||hasForbiddenKey(value))return false;const item=value as Partial<Envelope>;return typeof item.request_id==="string"&&(item.failure_code===null||typeof item.failure_code==="string")&&(item.case===null||isCase(item.case))&&(item.review===null||isReview(item.review))}
function isListEnvelope(value:unknown):value is ListEnvelope{if(!value||typeof value!=="object"||hasForbiddenKey(value))return false;const item=value as Partial<ListEnvelope>;return typeof item.request_id==="string"&&Array.isArray(item.cases)&&item.cases.every(isCase)&&typeof item.next_cursor==="string"&&typeof item.has_more==="boolean"&&(item.failure_code===null||typeof item.failure_code==="string")}
function isRevisionListEnvelope(value:unknown):value is RevisionListEnvelope{if(!value||typeof value!=="object"||hasForbiddenKey(value))return false;const item=value as Partial<RevisionListEnvelope>;return typeof item.request_id==="string"&&Array.isArray(item.revisions)&&item.revisions.every(isCase)&&typeof item.next_cursor==="string"&&typeof item.has_more==="boolean"&&(item.failure_code===null||typeof item.failure_code==="string")}
function isCase(value:unknown):value is CaseDocument{if(!value||typeof value!=="object")return false;const item=value as Partial<CaseDocument>;return item.schema_version==="workflow_evaluation_case.v2"&&typeof item.case_id==="string"&&typeof item.version==="number"&&Number.isInteger(item.version)&&item.version>=1&&Number.isInteger(item.previous_version)&&["created","baseline_promotion","case_revision"].includes(item.revision_kind??"")&&Array.isArray(item.change_codes)&&item.change_codes.every(code=>typeof code==="string")&&typeof item.name==="string"&&typeof item.baseline_run_id==="string"&&Array.isArray(item.expectations)&&item.expectations.every(isExpectation)&&typeof item.created_at==="string"&&typeof item.revised_at==="string"}
function isExpectation(value:unknown):value is CaseDocument["expectations"][number]{if(!value||typeof value!=="object")return false;const item=value as Record<string,unknown>;return typeof item.candidate_run_id==="string"&&["regression","improvement","changed","unchanged"].includes(String(item.expected_classification))}
function isReview(value:unknown):value is ReviewDocument{if(!value||typeof value!=="object")return false;const item=value as Partial<ReviewDocument>;return typeof item.case_id==="string"&&typeof item.version==="number"&&Number.isInteger(item.version)&&item.version>=1&&isRunProfile(item.run_profile)&&["passed","mismatch","inconclusive"].includes(item.outcome??"")&&Number.isInteger(item.matched)&&Number.isInteger(item.mismatched)&&Number.isInteger(item.inconclusive)&&Number.isInteger(item.unavailable)&&Array.isArray(item.items)&&item.items.every(isReviewItem)}
function isReviewItem(value:unknown):value is ReviewDocument["items"][number]{if(!value||typeof value!=="object")return false;const item=value as Record<string,unknown>;return typeof item.candidate_run_id==="string"&&typeof item.expected_classification==="string"&&typeof item.actual_classification==="string"&&typeof item.comparison_state==="string"&&["","workflow_run_comparison.v1","workflow_run_comparison.v2","workflow_run_comparison.v3"].includes(String(item.comparison_schema_version))&&isRunProfile(item.run_profile)&&["matched","mismatched","inconclusive","unavailable"].includes(String(item.outcome))&&Array.isArray(item.finding_codes)&&item.finding_codes.every(code=>typeof code==="string")&&typeof item.recommended_review_action==="string"}
function isRunProfile(value:unknown):value is WorkflowEvaluationReview["runProfile"]{return["workflow_standard.v1","workflow_rag_retrieval.v1","workflow_rag_application_invocation.v1","unavailable"].includes(String(value))}
function envelopeFailure(value:unknown,status:number):string{if(value&&typeof value==="object"){const item=value as Partial<Envelope>;if(typeof item.failure_code==="string")return`${item.failure_code}: ${item.failure_summary??""}`};return`workflow evaluation route failed with HTTP ${status}`}
