import type { WorkflowExecutorConsumerConfig } from "./workflowExecutorConsumer.ts";

export type WorkflowEvaluationExpectation={candidateRunId:string;expectedClassification:"regression"|"improvement"|"changed"|"unchanged"};
export type WorkflowEvaluationCase={caseId:string;name:string;baselineRunId:string;expectations:WorkflowEvaluationExpectation[];createdAt:string;requestId:string;auditRef:string};
export type WorkflowEvaluationReviewItem={candidateRunId:string;expectedClassification:string;actualClassification:string;comparisonState:string;outcome:"matched"|"mismatched"|"inconclusive"|"unavailable";findingCodes:string[];recommendedReviewAction:string};
export type WorkflowEvaluationReview={caseId:string;outcome:"passed"|"mismatch"|"inconclusive";matched:number;mismatched:number;inconclusive:number;unavailable:number;items:WorkflowEvaluationReviewItem[]};
type CaseDocument={schema_version:"workflow_evaluation_case.v1";case_id:string;name:string;workspace_id:string;application_id:string;baseline_run_id:string;expectations:Array<{candidate_run_id:string;expected_classification:WorkflowEvaluationExpectation["expectedClassification"]}>;created_at:string;actor_ref:string;request_id:string;audit_ref:string};
type ReviewDocument={case_id:string;outcome:WorkflowEvaluationReview["outcome"];matched:number;mismatched:number;inconclusive:number;unavailable:number;items:Array<{candidate_run_id:string;expected_classification:string;actual_classification:string;comparison_state:string;outcome:WorkflowEvaluationReviewItem["outcome"];finding_codes:string[];recommended_review_action:string}>};
type Envelope={request_id:string;workspace_id:string;application_id:string;case:CaseDocument|null;review:ReviewDocument|null;failure_code:string|null;failure_summary:string;audit_ref:string};
type ListEnvelope={request_id:string;workspace_id:string;application_id:string;cases:CaseDocument[];next_cursor:string;has_more:boolean;failure_code:string|null;failure_summary:string;audit_ref:string};

export async function createWorkflowEvaluationCase(applicationId:string,name:string,baselineRunId:string,expectations:WorkflowEvaluationExpectation[],config:WorkflowExecutorConsumerConfig):Promise<WorkflowEvaluationCase>{if(config.mode!=="dev_workflow_executor_http")throw new Error("Workflow evaluations are unavailable in offline mode.");const response=await fetch(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases`,{method:"POST",headers:{...evaluationHeaders(config,applicationId,true),"Content-Type":"application/json"},body:JSON.stringify({workspace_id:config.workspaceId,application_id:applicationId,name,baseline_run_id:baselineRunId,expectations:expectations.map(item=>({candidate_run_id:item.candidateRunId,expected_classification:item.expectedClassification}))})});const body:unknown=await response.json();if(!response.ok||!isEnvelope(body)||body.failure_code||!body.case)throw new Error(envelopeFailure(body,response.status));return mapCase(body.case)}
export async function listWorkflowEvaluationCases(applicationId:string,config:WorkflowExecutorConsumerConfig,cursor=""):Promise<{cases:WorkflowEvaluationCase[];nextCursor:string;hasMore:boolean}>{if(config.mode!=="dev_workflow_executor_http")return{cases:[],nextCursor:"",hasMore:false};const query=new URLSearchParams({workspace_id:config.workspaceId,application_id:applicationId,limit:"25"});if(cursor)query.set("cursor",cursor);const response=await fetch(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases?${query}`,{headers:evaluationHeaders(config,applicationId,false)});const body:unknown=await response.json();if(!response.ok||!isListEnvelope(body)||body.failure_code)throw new Error(envelopeFailure(body,response.status));return{cases:body.cases.map(mapCase),nextCursor:body.next_cursor,hasMore:body.has_more}}
export async function reviewWorkflowEvaluationCase(applicationId:string,caseId:string,config:WorkflowExecutorConsumerConfig):Promise<WorkflowEvaluationReview>{if(config.mode!=="dev_workflow_executor_http")throw new Error("Workflow evaluations are unavailable in offline mode.");const query=new URLSearchParams({workspace_id:config.workspaceId,application_id:applicationId});const response=await fetch(`${config.baseUrl}/v1/user-workspace/workflow-evaluation-cases/${encodeURIComponent(caseId)}/review?${query}`,{headers:evaluationHeaders(config,applicationId,false)});const body:unknown=await response.json();if(!response.ok||!isEnvelope(body)||body.failure_code||!body.review)throw new Error(envelopeFailure(body,response.status));return mapReview(body.review)}
function evaluationHeaders(config:WorkflowExecutorConsumerConfig,applicationId:string,write:boolean):HeadersInit{return{Accept:"application/json","X-Request-Id":`dev-workflow-evaluation-${applicationId}`,"X-RadishMind-Dev-Read-Identity":"dev-workflow-evaluation-consumer","X-RadishMind-Dev-Read-Tenant":config.tenantRef,"X-RadishMind-Dev-Read-Subject":config.subjectRef,"X-RadishMind-Dev-Read-Scopes":write?"workflow_evaluations:write,workflow_evaluations:read,workflow_runs:read":"workflow_evaluations:read,workflow_runs:read","X-RadishMind-Dev-Read-Audit":"audit_dev_workflow_evaluation_consumer","X-RadishMind-Dev-Workflow-Workspace":config.workspaceId,"X-RadishMind-Dev-Workflow-Application":applicationId}}
function mapCase(value:CaseDocument):WorkflowEvaluationCase{return{caseId:value.case_id,name:value.name,baselineRunId:value.baseline_run_id,expectations:value.expectations.map(item=>({candidateRunId:item.candidate_run_id,expectedClassification:item.expected_classification})),createdAt:value.created_at,requestId:value.request_id,auditRef:value.audit_ref}}
function mapReview(value:ReviewDocument):WorkflowEvaluationReview{return{caseId:value.case_id,outcome:value.outcome,matched:value.matched,mismatched:value.mismatched,inconclusive:value.inconclusive,unavailable:value.unavailable,items:value.items.map(item=>({candidateRunId:item.candidate_run_id,expectedClassification:item.expected_classification,actualClassification:item.actual_classification,comparisonState:item.comparison_state,outcome:item.outcome,findingCodes:item.finding_codes,recommendedReviewAction:item.recommended_review_action}))}}
function hasForbiddenKey(value:unknown):boolean{if(Array.isArray(value))return value.some(hasForbiddenKey);if(!value||typeof value!=="object")return false;const forbidden=new Set(["input_text","input_bytes","condition_values","condition_node_ids","output","output_preview","credential","endpoint","provider_raw_envelope","comparison"]);return Object.entries(value as Record<string,unknown>).some(([key,child])=>forbidden.has(key)||hasForbiddenKey(child))}
function isEnvelope(value:unknown):value is Envelope{if(!value||typeof value!=="object"||hasForbiddenKey(value))return false;const item=value as Partial<Envelope>;return typeof item.request_id==="string"&&(item.failure_code===null||typeof item.failure_code==="string")&&(item.case===null||isCase(item.case))&&(item.review===null||isReview(item.review))}
function isListEnvelope(value:unknown):value is ListEnvelope{if(!value||typeof value!=="object"||hasForbiddenKey(value))return false;const item=value as Partial<ListEnvelope>;return typeof item.request_id==="string"&&Array.isArray(item.cases)&&item.cases.every(isCase)&&typeof item.next_cursor==="string"&&typeof item.has_more==="boolean"&&(item.failure_code===null||typeof item.failure_code==="string")}
function isCase(value:unknown):value is CaseDocument{if(!value||typeof value!=="object")return false;const item=value as Partial<CaseDocument>;return item.schema_version==="workflow_evaluation_case.v1"&&typeof item.case_id==="string"&&typeof item.name==="string"&&typeof item.baseline_run_id==="string"&&Array.isArray(item.expectations)}
function isReview(value:unknown):value is ReviewDocument{if(!value||typeof value!=="object")return false;const item=value as Partial<ReviewDocument>;return typeof item.case_id==="string"&&["passed","mismatch","inconclusive"].includes(item.outcome??"")&&Array.isArray(item.items)}
function envelopeFailure(value:unknown,status:number):string{if(value&&typeof value==="object"){const item=value as Partial<Envelope>;if(typeof item.failure_code==="string")return `${item.failure_code}: ${item.failure_summary??""}`};return`workflow evaluation route failed with HTTP ${status}`}
