import assert from "node:assert/strict";
import test from "node:test";
import { WorkflowEvaluationDecisionConflict, createWorkflowEvaluationSuite, decideWorkflowEvaluationSuite, listWorkflowEvaluationDecisions, listWorkflowEvaluationSuites, reviewWorkflowEvaluationSuite } from "../src/features/control-plane-read/workflowEvaluationSuiteConsumer.ts";
import type { WorkflowExecutorConsumerConfig } from "../src/features/control-plane-read/workflowExecutorConsumer.ts";

const offline={mode:"sample",baseUrl:"",workspaceId:"workspace_demo",tenantRef:"tenant_demo",subjectRef:"subject_demo"} as WorkflowExecutorConsumerConfig;
const live={...offline,mode:"dev_workflow_executor_http",baseUrl:"http://127.0.0.1:7000"} as WorkflowExecutorConsumerConfig;
const digest="a".repeat(64);
const suite={schema_version:"workflow_evaluation_suite.v1",suite_id:"suite_1",name:"release review",workspace_id:"workspace_demo",application_id:"app_demo",case_refs:[{case_id:"eval_1",version:2}],current_decision_version:0,current_decision:"",created_at:"2026-07-11T00:00:00Z",actor_ref:"actor",request_id:"request",audit_ref:"audit"};
const review={suite_id:"suite_1",outcome:"passed",review_digest:digest,passed:1,mismatch:0,inconclusive:0,unavailable:0,items:[{case_id:"eval_1",version:2,name:"release review",outcome:"passed",matched:1,mismatched:0,inconclusive:0,unavailable:0,audit_ref:"audit_case"}]};
const decision={schema_version:"workflow_evaluation_release_decision.v1",decision_id:"decision_1",suite_id:"suite_1",version:1,decision:"approved",review_digest:digest,review_outcome:"passed",passed:1,mismatch:0,inconclusive:0,unavailable:0,created_at:"2026-07-11T00:01:00Z",actor_ref:"actor",request_id:"request",audit_ref:"audit"};
function envelope(extra:Record<string,unknown>={}){return{request_id:"request",workspace_id:"workspace_demo",application_id:"app_demo",suite:null,decision:null,review:null,failure_code:null,failure_summary:"",audit_ref:"audit",...extra}}

test("evaluation suites remain offline without fetching",async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error("unexpected")};try{assert.deepEqual(await listWorkflowEvaluationSuites("app_demo",offline),{suites:[],nextCursor:"",hasMore:false});assert.deepEqual(await listWorkflowEvaluationDecisions("app_demo","suite_1",offline),{decisions:[],nextCursor:"",hasMore:false});await assert.rejects(()=>createWorkflowEvaluationSuite("app_demo","review",[{caseId:"eval_1",version:2}],offline),/offline/);await assert.rejects(()=>reviewWorkflowEvaluationSuite("app_demo","suite_1",offline),/offline/);assert.equal(calls,0)}finally{globalThis.fetch=original}});

test("evaluation suite creates immutable exact references and lists history",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(input,init)=>{calls++;if(init?.method==="POST"){const body=JSON.parse(String(init.body));assert.deepEqual(body.case_refs,[{case_id:"eval_1",version:2}]);assert.equal(new Headers(init.headers).get("X-RadishMind-Dev-Read-Scopes"),"workflow_evaluations:write,workflow_evaluations:read,workflow_runs:read");return new Response(JSON.stringify(envelope({suite})),{status:200})}assert.match(String(input),/workflow-evaluation-suites\?/);return new Response(JSON.stringify({request_id:"request",suites:[suite],next_cursor:"",has_more:false,failure_code:null,failure_summary:""}),{status:200})};try{const created=await createWorkflowEvaluationSuite("app_demo","release review",[{caseId:"eval_1",version:2}],live);assert.deepEqual(created.caseRefs,[{caseId:"eval_1",version:2}]);const page=await listWorkflowEvaluationSuites("app_demo",live);assert.equal(page.suites[0]?.suiteId,"suite_1");assert.equal(calls,2)}finally{globalThis.fetch=original}});

test("evaluation suite reviews and records digest-bound decision",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(input,init)=>{calls++;if(String(input).includes("/review?"))return new Response(JSON.stringify(envelope({review})),{status:200});if(init?.method==="POST"){const body=JSON.parse(String(init.body));assert.equal(body.expected_decision_version,0);assert.equal(body.review_digest,digest);return new Response(JSON.stringify(envelope({suite:{...suite,current_decision_version:1,current_decision:"approved"},decision})),{status:200})}return new Response(JSON.stringify({request_id:"request",decisions:[decision],next_cursor:"",has_more:false,failure_code:null,failure_summary:""}),{status:200})};try{assert.equal((await reviewWorkflowEvaluationSuite("app_demo","suite_1",live)).items[0]?.version,2);const result=await decideWorkflowEvaluationSuite("app_demo","suite_1",0,"approved",digest,live);assert.equal(result.suite.currentDecisionVersion,1);assert.equal((await listWorkflowEvaluationDecisions("app_demo","suite_1",live)).decisions[0]?.decision,"approved");assert.equal(calls,3)}finally{globalThis.fetch=original}});

test("evaluation suite surfaces decision CAS conflict and rejects forbidden payload",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;if(calls===1)return new Response(JSON.stringify(envelope({suite:{...suite,current_decision_version:1,current_decision:"needs_review"},failure_code:"workflow_evaluation_suite_decision_conflict",failure_summary:"changed"})),{status:200});return new Response(JSON.stringify(envelope({suite:{...suite,input_text:"private"}})),{status:200})};try{await assert.rejects(()=>decideWorkflowEvaluationSuite("app_demo","suite_1",0,"approved",digest,live),error=>error instanceof WorkflowEvaluationDecisionConflict&&error.currentSuite.currentDecisionVersion===1);await assert.rejects(()=>createWorkflowEvaluationSuite("app_demo","release review",[{caseId:"eval_1",version:2}],live),/route failed/)}finally{globalThis.fetch=original}});
