import assert from"node:assert/strict";import test from"node:test";
import{createWorkflowEvaluationCase,listWorkflowEvaluationCases,reviewWorkflowEvaluationCase}from"../src/features/control-plane-read/workflowEvaluationConsumer.ts";import type{WorkflowExecutorConsumerConfig}from"../src/features/control-plane-read/workflowExecutorConsumer.ts";
const offline:WorkflowExecutorConsumerConfig={mode:"disabled",baseUrl:"http://127.0.0.1:7000",workspaceId:"workspace_demo",tenantRef:"tenant_demo",subjectRef:"subject_demo"};const live={...offline,mode:"dev_workflow_executor_http"}as WorkflowExecutorConsumerConfig;
const caseDoc={schema_version:"workflow_evaluation_case.v1",case_id:"eval_1",name:"release review",workspace_id:"workspace_demo",application_id:"app_demo",baseline_run_id:"run_base",expectations:[{candidate_run_id:"run_candidate",expected_classification:"regression"}],created_at:"2026-07-11T10:00:00Z",actor_ref:"subject_demo",request_id:"request_case",audit_ref:"audit_case"};
function envelope(extra:Record<string,unknown>={}){return{request_id:"request",workspace_id:"workspace_demo",application_id:"app_demo",case:null,review:null,failure_code:null,failure_summary:"",audit_ref:"audit",...extra}}
test("workflow evaluations remain offline without fetching",async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error("unexpected")};try{assert.deepEqual(await listWorkflowEvaluationCases("app_demo",offline),{cases:[],nextCursor:"",hasMore:false});await assert.rejects(()=>createWorkflowEvaluationCase("app_demo","case","run_a",[{candidateRunId:"run_b",expectedClassification:"changed"}],offline),/offline/);assert.equal(calls,0)}finally{globalThis.fetch=original}});
test("workflow evaluation creates sanitized ref-only case",async()=>{const original=globalThis.fetch;globalThis.fetch=async(input,init)=>{assert.equal(String(input),"http://127.0.0.1:7000/v1/user-workspace/workflow-evaluation-cases");const body=JSON.parse(String(init?.body));assert.equal(body.expectations[0].expected_classification,"regression");assert.equal(new Headers(init?.headers).get("X-RadishMind-Dev-Read-Scopes"),"workflow_evaluations:write,workflow_evaluations:read,workflow_runs:read");return new Response(JSON.stringify(envelope({case:caseDoc})),{status:200})};try{const value=await createWorkflowEvaluationCase("app_demo","release review","run_base",[{candidateRunId:"run_candidate",expectedClassification:"regression"}],live);assert.equal(value.caseId,"eval_1")}finally{globalThis.fetch=original}});
test("workflow evaluation lists and reviews batch outcome",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(input)=>{calls++;if(String(input).includes("/review?"))return new Response(JSON.stringify(envelope({review:{case_id:"eval_1",outcome:"passed",matched:1,mismatched:0,inconclusive:0,unavailable:0,items:[{candidate_run_id:"run_candidate",expected_classification:"regression",actual_classification:"regression",comparison_state:"comparable",outcome:"matched",finding_codes:["status_regressed"],recommended_review_action:"review_draft"}]}})),{status:200});return new Response(JSON.stringify({request_id:"request",workspace_id:"workspace_demo",application_id:"app_demo",cases:[caseDoc],next_cursor:"",has_more:false,failure_code:null,failure_summary:"",audit_ref:"audit"}),{status:200})};try{const page=await listWorkflowEvaluationCases("app_demo",live);assert.equal(page.cases[0]?.baselineRunId,"run_base");const review=await reviewWorkflowEvaluationCase("app_demo","eval_1",live);assert.equal(review.outcome,"passed");assert.equal(review.items[0]?.findingCodes[0],"status_regressed");assert.equal(calls,2)}finally{globalThis.fetch=original}});
test("workflow evaluation rejects forbidden nested payload",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify(envelope({case:{...caseDoc,output_preview:"private"}})),{status:200});try{await assert.rejects(()=>createWorkflowEvaluationCase("app_demo","release review","run_base",[{candidateRunId:"run_candidate",expectedClassification:"regression"}],live),/route failed/)}finally{globalThis.fetch=original}});
